### ISSUE TITLE
Swipe Page

### ISSUE THREAD

**Issue by akshire** [PlateSwipe/PlateSwipe#107]
This issue consists of creating a screen that proposes some recipes to the user and he will be able to say if he likes the recipe or if he does not care about the recipe. The page will  

Tasks to be done:
- [x] UI of Swipe Screen @AdriB02 
- [x] Model of a Recipe @2Fick 
- [x] ViewModel of Recipe @2Fick 
- [x] MealDB recipe Repository @akshire
- [x] Test the whole system together @2Fick  @akshire @AdriB02 

Linked to the user story #10

**Comment by AdriB02** [comment]
I am currently adapting the code to ensure compatibility with the model.
